version: '3'

services: 
    # angular:
    #     container_name: handi-tracker-ui
    #     build: ./handicap-helper
    #     ports:
    #         - '4200:4200'
    express: 
        container_name: handi-tracker-service
        restart: always
        build: ./backend
        ports: 
            - '80:3000'
        links:
            - mongo
    mongo: 
        container_name: mongo
        # command: ["mongod", "-f", "/etc/mongo/mongod.conf.orig"]
        image: mongo
        volumes: 
            - /mongo-volume:/data/db
        ports:
            - '27017:27017'